networks:
  regulus_network:
    driver: bridge

volumes:
  regulus_mysql_data:
  regulus_redis_data:

services:
  regulus_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: regulus-app
    container_name: regulus-app
    ports:
      - "80:80"
      - "5173:5173"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www
      - ./docker/nginx/regulus.conf:/etc/nginx/sites-available/default
      - ./storage/app:/var/www/storage/app
      - ./storage/framework:/var/www/storage/framework
      - ./storage/logs:/var/www/storage/logs
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      regulus_mailpit:
        condition: service_healthy
      regulus_mysql:
        condition: service_healthy
      regulus_redis:
        condition: service_healthy
      regulus_soketi:
        condition: service_started
    networks:
      - regulus_network
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=regulus-mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=regulus-redis
      - REDIS_PORT=6379
      - MAIL_HOST=regulus-mailpit
      - MAIL_PORT=1025
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=regulus-soketi
      - PUSHER_PORT=6001
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG:-}

  regulus_mysql:
    image: mysql:8.3.0
    container_name: regulus-mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - regulus_mysql_data:/var/lib/mysql
    networks:
      - regulus_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  regulus_redis:
    image: redis:7-alpine
    container_name: regulus-redis
    ports:
      - "63790:6379"
    volumes:
      - regulus_redis_data:/data
    networks:
      - regulus_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  regulus_soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: regulus-soketi
    environment:
      SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
      SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
      SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
    ports:
      - '${PUSHER_PORT:-6001}:6001'
      - '${PUSHER_METRICS_PORT:-9601}:9601'
    networks:
      - regulus_network

  regulus_mailpit:
    image: axllent/mailpit:latest
    container_name: regulus-mailpit
    ports:
      - "8027:8025"
      - "1027:1025"
    environment:
      MP_SMTP_PORT: 1025
      MP_HTTP_PORT: 8025
      MP_HOSTNAME: regulus-mailpit
    networks:
      - regulus_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/api/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 5